# Generated by Django 3.0.2 on 2020-02-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('running_dashboard', '0002_run_runner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'permissions': (('can_observe_all_runs', 'Can observe all runs'),)},
        ),
    ]
